In [1]:
import pandas as pd

In [2]:
team_stats = pd.read_csv('data/TeamStatistics.csv')
#player_stats = pd.read_csv('PlayerStatistics.csv')
game_stats = pd.read_csv('data/Games.csv')
team_salaries = pd.read_csv('data/NBA Payroll(1990-2023).csv')
team_sal_2022_2024 = pd.read_csv('data/2021-2024 aggregated Payroll.csv')

/tmp/ipykernel_510166/729060676.py:3: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  game_stats = pd.read_csv('data/Games.csv')

In [3]:
team_stats.head()

,gameId,gameDate,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,leadChanges,pointsFastBreak,pointsFromTurnovers,pointsInThePaint,pointsSecondChance,timesTied,timeoutsRemaining,seasonWins,seasonLosses,coachId
0,42400407,2025-06-22 20:00:00,Indiana,Pacers,1610612754,Oklahoma City,Thunder,1610612760,0,0,...,11.0,7.0,10.0,26.0,15.0,10.0,0.0,3.0,4.0,NaN
1,42400407,2025-06-22 20:00:00,Oklahoma City,Thunder,1610612760,Indiana,Pacers,1610612754,1,1,...,11.0,9.0,32.0,40.0,22.0,10.0,0.0,4.0,3.0,NaN
2,42400406,2025-06-19 20:30:00,Indiana,Pacers,1610612754,Oklahoma City,Thunder,1610612760,1,1,...,1.0,22.0,19.0,30.0,14.0,1.0,1.0,3.0,3.0,NaN
3,42400406,2025-06-19 20:30:00,Oklahoma City,Thunder,1610612760,Indiana,Pacers,1610612754,0,0,...,1.0,11.0,13.0,40.0,6.0,1.0,1.0,3.0,3.0,NaN
4,42400405,2025-06-16 20:30:00,Indiana,Pacers,1610612754,Oklahoma City,Thunder,1610612760,0,0,...,6.0,13.0,9.0,48.0,21.0,2.0,0.0,2.0,3.0,NaN

In [4]:
# Suppose gameDate is in YYYY-MM-DD format
team_stats['gameDate'] = pd.to_datetime(team_stats['gameDate'], format='mixed', utc=True)
team_stats['season'] = pd.to_datetime(team_stats['gameDate'])

def get_season_year(date):
    if date.month >= 7:  # July or later → season starts this year
        return date.year
    else:                # Before July → season started the previous year
        return date.year - 1

team_stats = team_stats.merge(
    game_stats[['gameId', 'gameType']],  # columns to bring over
    on='gameId',
    how='left'  # keep all rows from team_stats
)

team_stats['season'] = team_stats['gameDate'].apply(get_season_year)

team_salaries.rename(columns={'seasonStartYear' : 'season',
                              'team' : 'teamCity'}, inplace=True)

team_salaries = team_salaries[team_salaries['season'] >= 2000]

In [5]:
# Separate out playoff and regular season games
regular_season_team_stats = team_stats[team_stats['gameType'] == 'Regular Season']
playoff_team_stats = team_stats[team_stats['gameType'] == 'Playoffs']

In [6]:
# Basic aggregations
regular_season_team = (
    regular_season_team_stats.groupby(['season', 'teamId', 'teamName'])
    .agg(
        games_played=('gameId', 'count'),
        wins=('win', 'sum'),
        losses=('win', lambda x: (1 - x).sum()),
        avg_points=('teamScore', 'mean'),
        avg_opponent_points=('opponentScore', 'mean'),
        avg_point_diff=('plusMinusPoints', 'mean'),
        fg_pct=('fieldGoalsPercentage', 'mean'),
        three_pct=('threePointersPercentage', 'mean'),
        ft_pct=('freeThrowsPercentage', 'mean'),
        assists=('assists', 'mean'),
        rebounds=('reboundsTotal', 'mean'),
        turnovers=('turnovers', 'mean'),
        steals=('steals', 'mean'),
        blocks=('blocks', 'mean'),
        fastbreak_pts=('pointsFastBreak', 'mean'), # These values only appear in the year 2024... Perhaps they implemented new metrics?
        paint_pts=('pointsInThePaint', 'mean'), ##
        second_chance_pts=('pointsSecondChance', 'mean'), ##
        points_from_to=('pointsFromTurnovers', 'mean'), ##
        biggest_lead=('biggestLead', 'mean'), ##
        times_tied=('timesTied', 'mean'), ##
        lead_changes=('leadChanges', 'mean'), ##
        def_rebounds=('reboundsDefensive', 'mean'),
        off_rebounds=('reboundsOffensive', 'mean'),
        personal_fouls=('foulsPersonal', 'mean'),
        plus_minus_pts = ('plusMinusPoints', 'mean'),

    )
    .reset_index()
)
regular_season_team['off_efficiency'] = regular_season_team[['fg_pct', 'ft_pct', 'three_pct']].mean(axis=1)


playoff_season_team = (
    playoff_team_stats[playoff_team_stats['gameType'] == 'Playoffs']  # filter just to playoff games
    .groupby(['season', 'teamId', 'teamName'])
    .agg(
        playoff_games=('gameId', 'count'),
        playoff_wins=('win', 'sum'),
        playoff_losses=('win', lambda x: (1 - x).sum())
    )
    .reset_index()
)

# Derived features
regular_season_team['win_pct'] = regular_season_team['wins'] / regular_season_team['games_played']
regular_season_team['avg_margin'] = regular_season_team['avg_points'] - regular_season_team['avg_opponent_points']

numeric_cols = regular_season_team.select_dtypes(include='number').columns
regular_season_team[numeric_cols] = regular_season_team[numeric_cols].round(2)

In [7]:
# Merge regular season and playoff summaries
team_stats_full = pd.merge(
    regular_season_team,
    playoff_season_team,
    on=['season', 'teamId', 'teamName'],
    how='left'  # keep all regular-season teams, even if they didn't make playoffs
)
team_salaries = pd.concat(
    [team_salaries, team_sal_2022_2024],
    ignore_index=True
)
team_salaries.drop(columns=['Unnamed: 0', 'teamCity'], inplace=True)
team_salaries['teamName'] = team_salaries['teamName'].fillna('')
cols = ['payroll', 'inflationAdjPayroll']
team_salaries[cols] = (
    team_salaries[cols]
    .replace(r'[\$,]', '', regex=True)
    .astype(float)
)

#Merge salaries with team_stats
team_stats_full = pd.merge(
    team_stats_full,
    team_salaries,
    on = ['season', 'teamName'],
    how='left'
)

team_stats_full[['playoff_games', 'playoff_wins', 'playoff_losses']] = (
    team_stats_full[['playoff_games', 'playoff_wins', 'playoff_losses']].fillna(0)
)

In [8]:
team_salaries

     season      payroll  inflationAdjPayroll       teamName
0      2000   87395140.0          150209627.0  Trail Blazers
1      2000   74007738.0          127200145.0         Knicks
2      2000   73472329.0          126279916.0           Heat
3      2000   68977578.0          118554603.0           Nets
4      2000   59085969.0          101553484.0        Wizards
..      ...          ...                  ...            ...
801    2025  154852894.0                  NaN          Spurs
802    2025  150359238.0                  NaN          Magic
803    2025  146986348.0                  NaN           Jazz
804    2025  136475241.0                  NaN        Pistons
805    2025  121341369.0                  NaN        Raptors

[806 rows x 4 columns]

In [9]:
team_stats_full_2000_on = team_stats_full[team_stats_full['season'] >= 2000]

In [10]:
team_stats_full_2000_on[team_stats_full_2000_on['season']==2001]

,season,teamId,teamName,games_played,wins,losses,avg_points,avg_opponent_points,avg_point_diff,fg_pct,...,personal_fouls,plus_minus_pts,off_efficiency,win_pct,avg_margin,playoff_games,playoff_wins,playoff_losses,payroll,inflationAdjPayroll
940,2001,1610612737,Hawks,82,33,49,94.04,98.27,-4.01,0.44,...,20.76,-4.01,0.52,0.40,-4.23,0.0,0.0,0.0,51525207.0,85772381.0
941,2001,1610612738,Celtics,82,49,33,96.35,94.15,2.21,0.43,...,21.66,2.21,0.51,0.60,2.21,16.0,9.0,7.0,47515677.0,79097845.0
942,2001,1610612739,Cavaliers,82,29,53,95.27,98.60,-3.33,0.45,...,21.37,-3.33,0.53,0.35,-3.33,0.0,0.0,0.0,45649974.0,75992069.0
943,2001,1610612741,Bulls,82,21,61,89.45,97.99,-8.03,0.43,...,22.37,-8.03,0.50,0.26,-8.54,0.0,0.0,0.0,42592857.0,70902978.0
944,2001,1610612742,Mavericks,82,57,25,105.23,100.98,4.26,0.46,...,22.46,4.26,0.55,0.70,4.26,8.0,4.0,4.0,57960080.0,96484312.0
945,2001,1610612743,Nuggets,82,27,55,92.18,98.00,-5.41,0.43,...,22.84,-5.41,0.50,0.33,-5.82,0.0,0.0,0.0,54460475.0,90658629.0
946,2001,1610612744,Warriors,82,21,61,97.67,103.07,-5.40,0.43,...,22.98,-5.40,0.49,0.26,-5.40,0.0,0.0,0.0,47681152.0,79373305.0
947,2001,1610612745,Rockets,82,28,54,92.34,97.23,-4.89,0.43,...,18.00,-4.89,0.50,0.34,-4.89,0.0,0.0,0.0,49168169.0,81848694.0
948,2001,1610612746,Clippers,82,39,43,95.68,96.15,-0.46,0.45,...,19.80,-0.46,0.51,0.48,-0.46,0.0,0.0,0.0,33849932.0,56348909.0
949,2001,1610612747,Lakers,82,58,24,101.27,94.15,7.12,0.46,...,22.23,7.12,0.51,0.71,7.12,19.0,15.0,4.0,54262017.0,90328263.0
950,2001,1610612748,Heat,82,36,46,87.20,88.73,-1.54,0.44,...,22.51,-1.54,0.51,0.44,-1.54,0.0,0.0,0.0,53351186.0,88812030.0
951,2001,1610612749,Bucks,82,41,41,97.51,97.73,-0.22,0.46,...,21.80,-0.22,0.53,0.50,-0.22,0.0,0.0,0.0,56224266.0,93594760.0
952,2001,1610612750,Timberwolves,82,50,32,99.33,95.95,3.38,0.46,...,21.21,3.38,0.55,0.61,3.38,3.0,0.0,3.0,55093782.0,91712876.0
953,2001,1610612751,Nets,82,52,30,96.21,92.05,4.48,0.45,...,21.15,4.48,0.50,0.63,4.16,20.0,11.0,9.0,75193712.0,125172596.0
954,2001,1610612752,Knicks,82,30,52,91.63,95.62,-3.54,0.43,...,21.95,-3.54,0.53,0.37,-3.99,0.0,0.0,0.0,85993039.0,143149897.0
955,2001,1610612753,Magic,82,44,38,100.49,98.91,1.86,0.45,...,20.73,1.86,0.53,0.54,1.57,4.0,1.0,3.0,45984001.0,76548112.0
956,2001,1610612754,Pacers,82,42,40,96.80,96.54,0.27,0.45,...,22.88,0.27,0.52,0.51,0.27,5.0,2.0,3.0,53398621.0,88890997.0
957,2001,1610612755,76ers,82,43,39,90.99,89.39,1.60,0.44,...,20.06,1.60,0.51,0.52,1.60,5.0,2.0,3.0,58073366.0,96672896.0
958,2001,1610612756,Suns,82,36,46,95.15,95.83,-0.68,0.45,...,21.77,-0.68,0.51,0.44,-0.68,0.0,0.0,0.0,56596369.0,94214187.0
959,2001,1610612757,Trail Blazers,82,49,33,96.65,93.66,2.99,0.45,...,19.67,2.99,0.52,0.60,2.99,3.0,0.0,3.0,84292850.0,140319647.0
960,2001,1610612758,Kings,82,61,21,104.61,97.00,7.61,0.47,...,19.02,7.61,0.53,0.74,7.61,16.0,10.0,6.0,54921012.0,91425274.0
961,2001,1610612759,Spurs,82,58,24,96.73,90.52,6.21,0.46,...,19.21,6.21,0.52,0.71,6.21,10.0,4.0,6.0,45844814.0,76316410.0
962,2001,1610612760,SuperSonics,82,45,37,97.73,94.71,3.02,0.47,...,21.12,3.02,0.53,0.55,3.02,5.0,2.0,3.0,NaN,NaN
963,2001,1610612761,Raptors,82,42,40,91.39,91.83,-0.44,0.43,...,21.60,-0.44,0.51,0.51,-0.44,5.0,2.0,3.0,52657161.0,87656710.0
964,2001,1610612762,Jazz,82,44,38,95.99,95.10,1.17,0.45,...,24.04,1.17,0.52,0.54,0.89,4.0,1.0,3.0,52642362.0,87632078.0
965,2001,1610612763,Grizzlies,82,23,59,89.90,97.34,-7.44,0.44,...,19.16,-7.44,0.48,0.28,-7.44,0.0,0.0,0.0,50920631.0,84765963.0
966,2001,1610612764,Wizards,82,37,45,92.79,94.20,-1.15,0.44,...,21.50,-1.15,0.53,0.45,-1.40,0.0,0.0,0.0,54776087.0,91184019.0
967,2001,1610612765,Pistons,82,50,32,94.33,92.20,2.13,0.45,...,20.67,2.13,0.53,0.61,2.13,10.0,4.0,6.0,42417677.0,70611365.0
968,2001,1610612766,Hornets,82,44,38,93.90,92.94,0.96,0.44,...,21.30,0.96,0.52,0.54,0.96,9.0,4.0,5.0,49999445.0,83232496.0

In [11]:
team_stats_full_2000_on[team_stats_full_2000_on['payroll'].isna()]

,season,teamId,teamName,games_played,wins,losses,avg_points,avg_opponent_points,avg_point_diff,fg_pct,...,personal_fouls,plus_minus_pts,off_efficiency,win_pct,avg_margin,playoff_games,playoff_wins,playoff_losses,payroll,inflationAdjPayroll
933,2000,1610612760,SuperSonics,82,44,38,97.29,97.27,0.02,0.46,...,21.13,0.02,0.53,0.54,0.02,0.0,0.0,0.0,NaN,NaN
962,2001,1610612760,SuperSonics,82,45,37,97.73,94.71,3.02,0.47,...,21.12,3.02,0.53,0.55,3.02,5.0,2.0,3.0,NaN,NaN
992,2002,1610612760,SuperSonics,82,40,42,92.13,92.26,0.15,0.44,...,20.88,0.15,0.51,0.49,-0.12,0.0,0.0,0.0,NaN,NaN
1021,2003,1610612760,SuperSonics,82,37,45,97.12,97.76,-0.63,0.45,...,21.76,-0.63,0.53,0.45,-0.63,0.0,0.0,0.0,NaN,NaN
1050,2004,1610612760,SuperSonics,82,52,30,98.94,96.65,2.29,0.45,...,23.71,2.29,0.53,0.63,2.29,11.0,6.0,5.0,NaN,NaN
1080,2005,1610612760,SuperSonics,82,35,47,102.57,105.60,-3.02,0.46,...,23.57,-3.02,0.54,0.43,-3.02,0.0,0.0,0.0,NaN,NaN
1110,2006,1610612760,SuperSonics,82,31,51,99.15,102.04,-2.41,0.46,...,21.96,-2.41,0.53,0.38,-2.89,0.0,0.0,0.0,NaN,NaN
1140,2007,1610612760,SuperSonics,82,20,62,97.55,106.30,-8.59,0.45,...,20.49,-8.59,0.51,0.24,-8.76,0.0,0.0,0.0,NaN,NaN

In [12]:
team_stats_full_2000_on

,season,teamId,teamName,games_played,wins,losses,avg_points,avg_opponent_points,avg_point_diff,fg_pct,...,personal_fouls,plus_minus_pts,off_efficiency,win_pct,avg_margin,playoff_games,playoff_wins,playoff_losses,payroll,inflationAdjPayroll
911,2000,1610612737,Hawks,82,25,57,90.96,96.17,-5.00,0.43,...,22.72,-5.00,0.52,0.30,-5.21,0.0,0.0,0.0,39297129.0,6.754159e+07
912,2000,1610612738,Celtics,82,36,46,94.62,96.76,-2.13,0.43,...,23.80,-2.13,0.51,0.44,-2.13,0.0,0.0,0.0,51478707.0,8.847857e+07
913,2000,1610612739,Cavaliers,82,30,52,92.21,96.45,-4.24,0.44,...,23.22,-4.24,0.51,0.37,-4.24,0.0,0.0,0.0,49780549.0,8.555988e+07
914,2000,1610612741,Bulls,82,15,67,87.57,96.67,-9.10,0.43,...,23.20,-9.10,0.50,0.18,-9.10,0.0,0.0,0.0,29691907.0,5.103270e+07
915,2000,1610612742,Mavericks,82,53,29,100.48,96.20,4.28,0.46,...,23.26,4.28,0.55,0.65,4.28,10.0,4.0,6.0,52274842.0,8.984692e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1682,2024,1610612762,Jazz,82,16,66,110.33,119.87,-9.65,0.45,...,18.93,-9.65,0.53,0.20,-9.54,0.0,0.0,0.0,120288903.0,1.202889e+08
1683,2024,1610612763,Grizzlies,82,48,34,121.71,116.85,4.90,0.48,...,20.87,4.90,0.54,0.59,4.85,4.0,0.0,4.0,109430560.0,1.094306e+08
1684,2024,1610612764,Wizards,82,19,63,106.63,118.88,-12.40,0.44,...,19.81,-12.40,0.51,0.23,-12.24,0.0,0.0,0.0,123530476.0,1.235305e+08
1685,2024,1610612765,Pistons,82,44,38,115.50,113.60,1.90,0.48,...,20.67,1.90,0.54,0.54,1.90,6.0,2.0,4.0,124620724.0,1.246207e+08
1686,2024,1610612766,Hornets,80,18,62,105.38,114.31,-8.94,0.43,...,18.76,-8.94,0.52,0.22,-8.94,0.0,0.0,0.0,81361135.0,8.136114e+07

In [13]:
season_team_2024 = team_stats_full[team_stats_full['season'] == 2024]

In [14]:
pd.set_option('display.max_columns', None)
season_team_2024.sort_values(by='wins', ascending=False).head(30)

,season,teamId,teamName,games_played,wins,losses,avg_points,avg_opponent_points,avg_point_diff,fg_pct,three_pct,ft_pct,assists,rebounds,turnovers,steals,blocks,fastbreak_pts,paint_pts,second_chance_pts,points_from_to,biggest_lead,times_tied,lead_changes,def_rebounds,off_rebounds,personal_fouls,plus_minus_pts,off_efficiency,win_pct,avg_margin,playoff_games,playoff_wins,playoff_losses,payroll,inflationAdjPayroll
1680,2024,1610612760,Thunder,83,68,15,120.02,107.51,12.52,0.48,0.37,0.82,26.69,44.76,11.01,10.33,5.66,16.06,50.94,14.70,21.75,21.10,4.20,5.83,34.18,10.58,19.82,12.52,0.56,0.82,12.52,23.0,16.0,7.0,142314490.0,1.423145e+08
1659,2024,1610612739,Cavaliers,82,64,18,121.94,112.40,9.54,0.49,0.38,0.77,28.10,45.40,12.55,8.17,4.27,14.94,51.48,13.78,18.95,18.54,4.41,6.58,34.22,11.18,18.13,9.54,0.55,0.78,9.54,9.0,5.0,4.0,183853996.0,1.838540e+08
1658,2024,1610612738,Celtics,82,61,21,116.27,107.16,9.11,0.46,0.37,0.80,26.15,45.32,11.37,7.18,5.51,11.89,41.09,14.25,15.53,18.33,4.68,6.56,33.94,11.38,15.89,9.11,0.54,0.74,9.11,11.0,6.0,5.0,151001071.0,1.510011e+08
1665,2024,1610612745,Rockets,81,51,30,114.47,109.95,4.52,0.45,0.35,0.74,23.40,48.52,12.95,8.36,5.02,17.00,51.55,18.24,17.51,15.48,4.81,7.25,33.78,14.74,18.98,4.52,0.52,0.63,4.52,7.0,3.0,4.0,133733972.0,1.337340e+08
1672,2024,1610612752,Knicks,82,51,31,115.78,111.68,4.10,0.49,0.37,0.80,27.49,42.65,12.20,8.18,3.95,15.70,52.47,14.33,19.21,16.06,4.49,6.21,31.79,10.85,17.16,4.10,0.55,0.62,4.10,18.0,10.0,8.0,154710344.0,1.547103e+08
1663,2024,1610612743,Nuggets,82,50,32,120.76,116.87,3.89,0.51,0.38,0.77,31.00,45.74,13.55,8.00,4.90,20.15,58.54,14.37,16.98,14.98,4.59,5.76,34.54,11.21,17.61,3.89,0.55,0.61,3.89,14.0,7.0,7.0,100597315.0,1.005973e+08
1674,2024,1610612754,Pacers,82,50,32,117.37,115.13,2.23,0.49,0.37,0.79,29.24,41.83,12.21,8.46,5.46,17.50,51.02,11.22,18.28,13.51,5.48,7.13,32.66,9.17,18.70,2.23,0.55,0.61,2.23,23.0,15.0,8.0,126338563.0,1.263386e+08
1670,2024,1610612750,Timberwolves,82,49,33,114.29,109.29,5.00,0.47,0.38,0.79,26.12,44.32,13.74,7.98,4.95,13.57,47.28,15.10,17.74,14.52,5.02,7.07,33.24,11.07,18.27,5.00,0.55,0.60,5.00,15.0,9.0,6.0,167640688.0,1.676407e+08
1667,2024,1610612747,Lakers,80,49,31,113.45,112.36,1.09,0.48,0.37,0.79,25.85,42.34,13.11,7.66,4.49,14.96,48.18,12.30,16.11,14.40,3.90,6.38,32.69,9.65,17.35,1.09,0.55,0.61,1.09,5.0,1.0,4.0,196866948.0,1.968669e+08
1666,2024,1610612746,Clippers,81,49,32,112.75,108.47,4.28,0.48,0.38,0.79,25.11,43.62,13.86,9.42,4.51,15.79,51.41,12.85,19.43,15.25,4.77,6.81,33.44,10.17,18.41,4.28,0.55,0.60,4.28,7.0,3.0,4.0,199610412.0,1.996104e+08
1683,2024,1610612763,Grizzlies,82,48,34,121.71,116.85,4.90,0.48,0.37,0.79,28.41,47.35,14.96,8.85,5.63,16.78,56.07,16.33,18.49,15.94,4.80,6.63,34.38,12.88,20.87,4.90,0.54,0.59,4.85,4.0,0.0,4.0,109430560.0,1.094306e+08
1664,2024,1610612744,Warriors,82,48,34,113.79,110.49,3.30,0.45,0.36,0.76,29.10,45.38,13.20,9.40,4.78,14.69,45.14,15.54,19.89,14.96,4.42,6.36,32.83,12.55,19.16,3.30,0.52,0.59,3.30,12.0,5.0,7.0,218741860.0,2.187419e+08
1669,2024,1610612749,Bucks,82,48,34,115.34,112.72,2.62,0.49,0.39,0.75,25.44,43.38,12.90,7.28,4.68,13.27,44.00,11.57,15.38,14.02,5.66,7.01,35.17,8.21,17.99,2.62,0.54,0.59,2.62,5.0,1.0,4.0,200895917.0,2.008959e+08
1685,2024,1610612765,Pistons,82,44,38,115.50,113.60,1.90,0.48,0.36,0.77,26.40,44.76,14.10,7.95,5.26,18.42,52.91,14.91,19.05,13.20,4.99,6.51,33.40,11.35,20.67,1.90,0.54,0.54,1.90,6.0,2.0,4.0,124620724.0,1.246207e+08
1673,2024,1610612753,Magic,82,41,41,104.01,104.27,-0.25,0.45,0.32,0.77,22.95,42.00,13.12,8.85,5.94,13.62,45.39,13.78,18.77,12.72,5.06,6.66,30.69,11.16,20.16,-0.25,0.51,0.50,-0.26,5.0,1.0,4.0,123147189.0,1.231472e+08
1657,2024,1610612737,Hawks,81,40,41,118.46,119.56,-1.10,0.47,0.36,0.77,29.72,44.56,14.69,9.72,5.11,17.21,55.32,14.59,19.18,11.74,5.52,7.36,32.64,11.91,19.09,-1.10,0.54,0.49,-1.10,0.0,0.0,0.0,138433279.0,1.384333e+08
1678,2024,1610612758,Kings,82,40,42,115.73,115.26,0.48,0.48,0.36,0.81,26.45,44.20,12.63,7.56,4.35,14.30,47.98,14.35,17.40,12.87,5.18,8.06,33.21,10.99,18.88,0.48,0.55,0.49,0.48,0.0,0.0,0.0,156110927.0,1.561109e+08
1661,2024,1610612741,Bulls,82,39,43,117.80,119.37,-1.56,0.47,0.37,0.81,29.06,45.85,13.94,7.57,4.71,18.50,50.78,13.02,15.40,11.96,4.70,7.23,35.79,10.06,17.61,-1.56,0.55,0.48,-1.56,0.0,0.0,0.0,130231084.0,1.302311e+08
1662,2024,1610612742,Mavericks,82,39,43,114.20,115.39,-1.20,0.48,0.36,0.77,25.24,43.05,13.30,7.76,5.43,15.10,50.84,13.77,16.88,12.91,5.14,6.78,32.95,10.10,17.78,-1.20,0.54,0.48,-1.20,0.0,0.0,0.0,84224223.0,8.422422e+07
1668,2024,1610612748,Heat,82,37,45,110.60,110.04,0.56,0.47,0.37,0.80,26.41,43.39,12.63,8.15,3.83,14.30,47.15,11.99,16.40,13.80,5.27,6.62,33.66,9.73,15.55,0.56,0.54,0.45,0.56,4.0,0.0,4.0,182500649.0,1.825006e+08
1676,2024,1610612756,Suns,82,36,46,113.62,116.62,-3.00,0.48,0.38,0.81,27.77,42.49,13.24,7.23,4.78,12.72,42.32,12.48,15.80,11.06,4.64,6.22,32.94,9.55,17.94,-3.00,0.55,0.44,-3.00,0.0,0.0,0.0,184248801.0,1.842488e+08
1677,2024,1610612757,Trail Blazers,82,36,46,110.89,113.87,-2.98,0.45,0.34,0.76,23.80,44.77,15.12,8.27,5.28,15.76,48.85,16.65,17.79,11.84,4.49,6.04,31.41,13.35,19.00,-2.98,0.52,0.44,-2.98,0.0,0.0,0.0,163847187.0,1.638472e+08
1679,2024,1610612759,Spurs,81,34,47,112.69,115.15,-2.49,0.47,0.36,0.78,28.68,43.74,13.16,8.26,5.58,16.01,47.26,12.54,17.02,11.74,5.11,6.59,32.76,10.98,16.64,-2.49,0.53,0.42,-2.46,0.0,0.0,0.0,85799581.0,8.579958e+07
1681,2024,1610612761,Raptors,82,30,52,110.87,115.16,-4.29,0.46,0.35,0.74,28.54,45.12,14.68,8.10,4.24,18.12,53.44,15.57,18.49,11.15,4.66,7.18,32.51,12.61,21.20,-4.29,0.52,0.37,-4.29,0.0,0.0,0.0,126987007.0,1.269870e+08
1671,2024,1610612751,Nets,82,26,56,105.11,112.22,-7.11,0.44,0.34,0.79,25.16,41.30,13.88,7.79,4.29,14.27,43.54,12.95,17.13,9.71,5.18,6.83,30.40,10.90,20.71,-7.11,0.52,0.32,-7.11,0.0,0.0,0.0,122754431.0,1.227544e+08
1675,2024,1610612755,76ers,82,24,58,109.61,115.84,-6.23,0.45,0.34,0.78,23.18,39.79,12.84,9.17,4.46,15.68,46.83,13.09,18.67,9.62,5.27,6.66,29.40,10.39,18.98,-6.23,0.53,0.29,-6.23,0.0,0.0,0.0,205347786.0,2.053478e+08
1660,2024,1610612740,Pelicans,81,21,60,109.86,119.36,-9.49,0.45,0.34,0.75,25.78,43.56,13.98,8.60,5.22,16.48,49.80,15.59,16.64,8.16,4.70,6.81,31.41,12.15,18.33,-9.49,0.52,0.26,-9.49,0.0,0.0,0.0,129776021.0,1.297760e+08
1684,2024,1610612764,Wizards,82,19,63,106.63,118.88,-12.40,0.44,0.33,0.77,25.04,43.78,14.94,7.54,5.14,15.77,45.54,12.67,14.72,7.35,4.49,6.37,33.23,10.54,19.81,-12.40,0.51,0.23,-12.24,0.0,0.0,0.0,123530476.0,1.235305e+08
1686,2024,1610612766,Hornets,80,18,62,105.38,114.31,-8.94,0.43,0.34,0.78,24.34,45.19,14.89,7.38,4.49,11.73,45.11,16.28,14.76,7.10,3.96,5.20,32.90,12.29,18.76,-8.94,0.52,0.22,-8.94,0.0,0.0,0.0,81361135.0,8.136114e+07
1682,2024,1610612762,Jazz,82,16,66,110.33,119.87,-9.65,0.45,0.35,0.78,25.47,45.46,16.47,6.77,4.43,13.87,47.24,14.68,13.13,9.27,4.33,6.01,33.43,12.02,18.93,-9.65,0.53,0.20,-9.54,0.0,0.0,0.0,120288903.0,1.202889e+08

In [15]:
season_team_2024.columns

Index(['season', 'teamId', 'teamName', 'games_played', 'wins', 'losses',
       'avg_points', 'avg_opponent_points', 'avg_point_diff', 'fg_pct',
       'three_pct', 'ft_pct', 'assists', 'rebounds', 'turnovers', 'steals',
       'blocks', 'fastbreak_pts', 'paint_pts', 'second_chance_pts',
       'points_from_to', 'biggest_lead', 'times_tied', 'lead_changes',
       'def_rebounds', 'off_rebounds', 'personal_fouls', 'plus_minus_pts',
       'off_efficiency', 'win_pct', 'avg_margin', 'playoff_games',
       'playoff_wins', 'playoff_losses', 'payroll', 'inflationAdjPayroll'],
      dtype='object')

In [16]:
team_stats_full_2000_on.to_csv("Agg_Team_Data_2000-2024.csv", index=False)